[libraries]
accompanist-adapter = { group = "com.google.accompanist", name = "accompanist-themeadapter-material3", version = "0.31.3-beta" }
android-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "android-activity" }
android-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "android-activity" }
android-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.6.1" }
android-browser = { group = "androidx.browser", name = "browser", version = "1.7.0" }
android-compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "android-compose" }
android-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "android-compose" }
android-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "android-compose" }
android-compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended", version = "1.5.4" }
android-compose-material3 = { group = "androidx.compose.material3", name = "material3", version = "1.2.0-beta02" }
android-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "android-compose" }
android-compose-ui-test-junit = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "android-compose" }
android-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "android-compose" }
android-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "android-compose" }
android-constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.4" }
android-constraintLayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version = "1.0.1" }
android-core = { group = "androidx.core", name = "core-ktx", version = "1.12.0" }
android-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "android-fragment" }
android-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "android-fragment" }
android-fragment-testing = { group = "androidx.fragment", name = "fragment-testing", version.ref = "android-fragment" }
android-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "android-lifecycle" }
android-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "android-lifecycle" }
android-material = { group = "com.google.android.material", name = "material", version = "1.11.0" }
android-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-plugin" }
android-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "android-room" }
android-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "android-room" }
android-test-core = { group = "androidx.test", name = "core-ktx", version = "1.5.0" }
android-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "android-test-espresso" }
android-test-espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "android-test-espresso" }
android-test-junit = { group = "androidx.test.ext", name = "junit-ktx", version = "1.1.5" }
android-test-runner = { group = "androidx.test", name = "runner", version = "1.5.0" }
assertk = { group = "com.willowtreeapps.assertk", name = "assertk", version = "0.27.0" }
autos = { group = "br.com.orcinus.orca.autos", name = "autos", version = "1.0.6" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version = "2.4.0" }
junit = { group = "junit", name = "junit", version = "4.13.2" }
jsoup = { group = "org.jsoup", name = "jsoup", version = "1.16.2" }
kotlin-compiler-embeddable = { group = "org.jetbrains.kotlin", name = "kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.5.1" }
kotlin-symbolProcessor = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "kotlin-symbolProcessor" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kctfork-ksp = { group = "dev.zacsweers.kctfork", name = "ksp", version = "0.4.0" }
kotlinPoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version = "1.14.2" }
ktor-client-contentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
lint-api = { group = "com.android.tools.lint", name = "lint-api", version.ref = "lint" }
lint-tests = { group = "com.android.tools.lint", name = "lint-tests", version.ref = "lint" }
loadable = { group = "com.jeanbarrossilva.loadable", name = "loadable", version.ref = "loadable" }
loadable-list = { group = "com.jeanbarrossilva.loadable", name = "loadable-list", version.ref = "loadable" }
loadable-placeholder = { group = "com.jeanbarrossilva.loadable", name = "loadable-placeholder", version.ref = "loadable" }
loadable-placeholder-test = { group = "com.jeanbarrossilva.loadable", name = "loadable-placeholder-test", version.ref = "loadable" }
mockk = { group = "io.mockk", name = "mockk-android", version = "1.13.7" }
openTest4J = { group = "org.opentest4j", name = "opentest4j", version = "1.3.0" }
paginate = { group = "com.chrynan.paginate", name = "paginate-core", version = "0.3.0" }
robolectric = { group = "org.robolectric", name = "robolectric", version = "4.12" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version = "2.0.7" }
spotless = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }
time4j = { group = "net.time4j", name = "time4j-android", version = "4.8-2021a" }
turbine = { group = "app.cash.turbine", name = "turbine", version = "1.0.0" }
zoomable = { group = "net.engawapg.lib", name = "zoomable", version = "1.6.0-beta2" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
android-maps-secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version = "2.0.1" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "3.1.0" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-symbolProcessor = { id = "com.google.devtools.ksp", version.ref = "kotlin-symbolProcessor" }
lint = { id = "com.android.lint", version.ref = "android-plugin" }
moduleDependencyGraph = { id = "com.savvasdalkitsis.module-dependency-graph", version = "0.10" }
orca-setup-android-library = { id = "br.com.orcinus.orca.setup.android.library" }
orca-setup-doc = { id = "br.com.orcinus.orca.setup.doc" }
orca-setup-formatting = { id = "br.com.orcinus.orca.setup.formatting" }
orca-setup-hooks = { id = "br.com.orcinus.orca.setup.hooks" }
orca-setup-java = { id = "br.com.orcinus.orca.setup.java" }
orca-setup-kotlin = { id = "br.com.orcinus.orca.setup.kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[versions]
android-activity = "1.7.0"
android-compose = "1.6.0-rc01"
android-compose-compiler = "1.5.11"
android-fragment = "1.6.2"
android-lifecycle = "2.7.0"
android-plugin = "8.3.1"
android-room = "2.6.1"
android-sdk-min = "28"
android-sdk-target = "34"
android-test-espresso = "3.5.0"
java = "17"
kotlin = "1.9.23"
kotlin-coroutines = "1.8.0"
kotlin-symbolProcessor = "1.9.23-1.0.19"
ktor = "2.3.2"
lint = "31.3.1"
loadable = "1.6.9"
spotless = "6.22.0"
